---
- name: Hardened sshd_config is used
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  changed_when: true
  notify: Restart sshd

- name: Hardened ssh_config is used
  ansible.builtin.copy:
    src: ssh_config
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'
  changed_when: true
  notify: Restart sshd
